// champions.js — all champion definitions with stats + unique spell kits

export const CHAMPIONS = {
    // ==================== MELEE CHAMPIONS ====================
    orc: {
        id: 'orc',
        name: 'Orc Warrior',
        role: 'Melee Bruiser',
        class: 'melee',
        color: '#4CAF50',
        colorDark: '#2E7D32',
        icon: '⚔️',
        size: 34,
        hp: 150,
        speed: 140,
        attackDamage: 20,
        attackRange: 40,
        attackSpeed: 1.0,
        armor: 5,
        magicResist: 3,
        spells: ['cleave', 'stomp', 'charge', 'berserk'],
        description: 'A hardy frontliner who charges into battle.',
    },
    elf: {
        id: 'elf',
        name: 'Dark Elf',
        role: 'Melee Assassin',
        class: 'melee',
        color: '#7B1FA2',
        colorDark: '#4A148C',
        icon: '🗡️',
        size: 30,
        hp: 100,
        speed: 175,
        attackDamage: 25,
        attackRange: 35,
        attackSpeed: 1.3,
        armor: 2,
        magicResist: 2,
        spells: ['shadow_strike', 'vanish', 'backstab', 'death_mark'],
        description: 'Strikes from the shadows with lethal precision.',
    },
    paladin: {
        id: 'paladin',
        name: 'Paladin',
        role: 'Tank / Support',
        class: 'melee',
        color: '#FDD835',
        colorDark: '#F9A825',
        icon: '🛡️',
        size: 36,
        hp: 180,
        speed: 125,
        attackDamage: 15,
        attackRange: 38,
        attackSpeed: 0.9,
        armor: 8,
        magicResist: 6,
        spells: ['holy_strike', 'shield_bash', 'divine_light', 'holy_nova'],
        description: 'A bulwark of light who endures and protects.',
    },
    demon_slayer: {
        id: 'demon_slayer',
        name: 'Demon Slayer',
        role: 'Elemental Hybrid',
        class: 'melee',
        color: '#00BCD4',
        colorDark: '#00838F',
        icon: '🌊',
        size: 32,
        hp: 130,
        speed: 150,
        attackDamage: 22,
        attackRange: 38,
        attackSpeed: 1.05,
        armor: 4,
        magicResist: 4,
        spells: ['water_breathing', 'flame_breathing', 'thunder_breathing', 'sun_dance'],
        description: 'Wields ancient breathing techniques to slay demons.',
    },
    saiyan: {
        id: 'saiyan',
        name: 'Saiyan',
        role: 'Ramp-up Brawler',
        class: 'melee',
        color: '#FF1744',
        colorDark: '#B71C1C',
        icon: '🔥',
        size: 34,
        hp: 160,
        speed: 145,
        attackDamage: 22,
        attackRange: 36,
        attackSpeed: 0.95,
        armor: 5,
        magicResist: 3,
        spells: ['ki_wave', 'instant_transmission', 'kaioken_punch', 'spirit_bomb'],
        description: 'A legendary warrior who teleports into the fray and grows stronger with every battle.',
    },

    // ==================== RANGED CHAMPIONS ====================
    pyro: {
        id: 'pyro',
        name: 'Pyromancer',
        role: 'Ranged Mage',
        class: 'ranged',
        color: '#FF5722',
        colorDark: '#BF360C',
        icon: '🔥',
        size: 28,
        hp: 75,
        speed: 140,
        attackDamage: 14,
        attackRange: 160,
        attackSpeed: 0.8,
        armor: 1,
        magicResist: 5,
        spells: ['fireball', 'flame_wall', 'combustion', 'meteor'],
        description: 'Wields devastating fire magic from a distance.',
    },
    shadow_hunter: {
        id: 'shadow_hunter',
        name: 'Shadow Hunter',
        role: 'Precision Marksman',
        class: 'ranged',
        color: '#78909C',
        colorDark: '#455A64',
        icon: '🏹',
        size: 28,
        hp: 85,
        speed: 160,
        attackDamage: 20,
        attackRange: 175,
        attackSpeed: 1.15,
        armor: 2,
        magicResist: 3,
        spells: ['piercing_shot', 'hunters_focus', 'tumble', 'deadeye'],
        description: 'A precision marksman who kites foes and pierces them from afar.',
    },
    ronin: {
        id: 'ronin',
        name: 'Ronin',
        role: 'Ninja Caster',
        class: 'ranged',
        color: '#FF6D00',
        colorDark: '#BF360C',
        icon: '🌀',
        size: 30,
        hp: 90,
        speed: 160,
        attackDamage: 18,
        attackRange: 140,
        attackSpeed: 1.0,
        armor: 3,
        magicResist: 6,
        spells: ['rasen_shuriken', 'shadow_clone', 'fire_style', 'sage_storm'],
        description: 'A wandering warrior armed with forbidden elemental jutsu.',
    },
};

export const CHAMPION_IDS = Object.keys(CHAMPIONS);
