// enemies.js — enemy type definitions for dungeon crawler

export const ENEMIES = {
    goblin: {
        id: 'goblin',
        name: 'Goblin',
        color: '#8B4513',
        colorDark: '#5D3A1A',
        icon: 'G',
        size: 28,
        hp: 40,
        speed: 80,
        attackDamage: 11,
        attackRange: 30,
        attackSpeed: 0.9,
        armor: 0,
        magicResist: 0,
        xpReward: 15,
        goldReward: 7,
        aggroRange: 180,
        leashRange: 300,
        aiBehavior: 'melee',
        _sprite: { gridCols: 4, frameSize: 28, states: { idle: [0,1,2,3], walk: [4,5,6,7], attack: [8,9,10,11], death: [12,13,14,15] } },
    },
    bat: {
        id: 'bat',
        name: 'Bat',
        color: '#4A148C',
        colorDark: '#311B92',
        icon: 'B',
        size: 20,
        hp: 18,
        speed: 140,
        attackDamage: 8,
        attackRange: 22,
        attackSpeed: 1.5,
        armor: 0,
        magicResist: 1,
        xpReward: 10,
        goldReward: 4,
        aggroRange: 250,
        leashRange: 350,
        aiBehavior: 'flier',
        _sprite: { gridCols: 4, frameSize: 20, states: { idle: [0,1,2,3], walk: [4,5,6,7], attack: [8,9,10,11], death: [12,13,14,15] } },
    },
    slime: {
        id: 'slime',
        name: 'Slime',
        color: '#2E7D32',
        colorDark: '#1B5E20',
        icon: 'S',
        size: 30,
        hp: 85,
        speed: 60,
        attackDamage: 14,
        attackRange: 26,
        attackSpeed: 0.5,
        armor: 3,
        magicResist: 3,
        xpReward: 20,
        goldReward: 11,
        aggroRange: 150,
        leashRange: 250,
        aiBehavior: 'slow_chase',
        _sprite: { gridCols: 4, frameSize: 30, states: { idle: [0,1,2,3], walk: [4,5,6,7], attack: [8,9,10,11], death: [12,13,14,15] } },
    },
    skeleton: {
        id: 'skeleton',
        name: 'Skeleton Archer',
        color: '#BDBDBD',
        colorDark: '#757575',
        icon: 'A',
        size: 32,
        hp: 45,
        speed: 65,
        attackDamage: 14,
        attackRange: 150,
        attackSpeed: 0.7,
        armor: 1,
        magicResist: 0,
        xpReward: 25,
        goldReward: 13,
        aggroRange: 300,
        leashRange: 400,
        aiBehavior: 'ranged',
        _sprite: { gridCols: 4, frameSize: 32, states: { idle: [0,1,2,3], walk: [4,5,6,7], attack: [8,9,10,11], death: [12,13,14,15] } },
    },
    orc_warrior: {
        id: 'orc_warrior',
        name: 'Orc Warrior',
        color: '#556B2F',
        colorDark: '#3E4F1E',
        icon: 'O',
        size: 34,
        hp: 90,
        speed: 70,
        attackDamage: 20,
        attackRange: 35,
        attackSpeed: 0.8,
        armor: 4,
        magicResist: 2,
        xpReward: 35,
        goldReward: 18,
        aggroRange: 200,
        leashRange: 350,
        aiBehavior: 'melee',
        _sprite: { gridCols: 4, frameSize: 34, states: { idle: [0,1,2,3], walk: [4,5,6,7], attack: [8,9,10,11], death: [12,13,14,15] } },
    },
    demon_hound: {
        id: 'demon_hound',
        name: 'Demon Hound',
        color: '#8B0000',
        colorDark: '#4A0000',
        icon: 'H',
        size: 28,
        hp: 70,
        speed: 150,
        attackDamage: 18,
        attackRange: 28,
        attackSpeed: 1.2,
        armor: 2,
        magicResist: 3,
        xpReward: 30,
        goldReward: 15,
        aggroRange: 280,
        leashRange: 400,
        aiBehavior: 'fast_chase',
        _sprite: { gridCols: 4, frameSize: 28, states: { idle: [0,1,2,3], walk: [4,5,6,7], attack: [8,9,10,11], death: [12,13,14,15] } },
    },
    necromancer: {
        id: 'necromancer',
        name: 'Necromancer',
        color: '#4B0082',
        colorDark: '#2E0054',
        icon: 'N',
        size: 32,
        hp: 60,
        speed: 60,
        attackDamage: 20,
        attackRange: 180,
        attackSpeed: 0.6,
        armor: 1,
        magicResist: 5,
        xpReward: 45,
        goldReward: 25,
        aggroRange: 350,
        leashRange: 450,
        aiBehavior: 'ranged_magic',
        _sprite: { gridCols: 4, frameSize: 32, states: { idle: [0,1,2,3], walk: [4,5,6,7], attack: [8,9,10,11], death: [12,13,14,15] } },
    },
    giant_spider: {
        id: 'giant_spider',
        name: 'Giant Spider',
        color: '#3E2723',
        colorDark: '#1B0000',
        icon: 'P',
        size: 36,
        hp: 100,
        speed: 100,
        attackDamage: 16,
        attackRange: 32,
        attackSpeed: 1.1,
        armor: 3,
        magicResist: 1,
        xpReward: 40,
        goldReward: 21,
        aggroRange: 220,
        leashRange: 320,
        aiBehavior: 'fast_chase',
        _sprite: { gridCols: 4, frameSize: 36, states: { idle: [0,1,2,3], walk: [4,5,6,7], attack: [8,9,10,11], death: [12,13,14,15] } },
    },
    dark_knight: {
        id: 'dark_knight',
        name: 'Dark Knight',
        color: '#212121',
        colorDark: '#000000',
        icon: 'K',
        size: 38,
        hp: 140,
        speed: 60,
        attackDamage: 26,
        attackRange: 38,
        attackSpeed: 0.7,
        armor: 6,
        magicResist: 4,
        xpReward: 60,
        goldReward: 35,
        aggroRange: 180,
        leashRange: 300,
        aiBehavior: 'melee',
        _sprite: { gridCols: 4, frameSize: 38, states: { idle: [0,1,2,3], walk: [4,5,6,7], attack: [8,9,10,11], death: [12,13,14,15] } },
    },
    fire_elemental: {
        id: 'fire_elemental',
        name: 'Fire Elemental',
        color: '#FF6D00',
        colorDark: '#BF360C',
        icon: 'F',
        size: 32,
        hp: 55,
        speed: 90,
        attackDamage: 22,
        attackRange: 120,
        attackSpeed: 0.7,
        armor: 0,
        magicResist: 8,
        xpReward: 50,
        goldReward: 28,
        aggroRange: 300,
        leashRange: 400,
        aiBehavior: 'ranged_magic',
        _sprite: { gridCols: 4, frameSize: 32, states: { idle: [0,1,2,3], walk: [4,5,6,7], attack: [8,9,10,11], death: [12,13,14,15] } },
    },
    // ════════════════════════════════════════════════════════════════
    //  HORROR CHAMPIONS — relentless stalkers with full Q/W/E/R kits.
    //  `_hunter` lets them sense the player through walls (within aggroRange)
    //  and never disengage. `_horror` routes them to the nightmare renderer.
    // ════════════════════════════════════════════════════════════════
    // NOTE: damage + aggroRange tuned DOWN for playability — they still hunt
    // relentlessly (never leash) and sense through walls, but only once you're
    // within a moderate range, so the whole floor no longer swarms you at once.
    smiler: {
        id: 'smiler', name: 'The Smiling Man', color: '#e8e8e8', colorDark: '#8a8a8a', icon: '☻',
        size: 38, hp: 55, speed: 128, attackDamage: 7, attackRange: 30, attackSpeed: 0.9,
        armor: 1, magicResist: 2, xpReward: 40, goldReward: 20,
        aggroRange: 360, leashRange: 100000, aiBehavior: 'fast_chase', _hunter: true, _horror: 'smiler',
    },
    nun: {
        id: 'nun', name: 'The Veiled Nun', color: '#2a2433', colorDark: '#15111c', icon: '✝',
        size: 40, hp: 65, speed: 56, attackDamage: 8, attackRange: 220, attackSpeed: 0.55,
        armor: 1, magicResist: 6, xpReward: 50, goldReward: 26,
        aggroRange: 380, leashRange: 100000, aiBehavior: 'ranged_magic', _hunter: true, _horror: 'nun',
    },
    crawler: {
        id: 'crawler', name: 'The Crawler', color: '#7a5230', colorDark: '#3a2616', icon: '⩜',
        size: 34, hp: 48, speed: 142, attackDamage: 7, attackRange: 28, attackSpeed: 1.0,
        armor: 0, magicResist: 1, xpReward: 38, goldReward: 18,
        aggroRange: 340, leashRange: 100000, aiBehavior: 'fast_chase', _hunter: true, _horror: 'crawler',
    },
    weeper: {
        id: 'weeper', name: 'The Weeping Child', color: '#9fb4c2', colorDark: '#566976', icon: '☂',
        size: 26, hp: 44, speed: 72, attackDamage: 6, attackRange: 210, attackSpeed: 0.65,
        armor: 0, magicResist: 3, xpReward: 36, goldReward: 18,
        aggroRange: 380, leashRange: 100000, aiBehavior: 'ranged_magic', _hunter: true, _horror: 'weeper',
    },
    butcher: {
        id: 'butcher', name: 'The Butcher', color: '#7d3030', colorDark: '#3e1515', icon: '🔪',
        size: 44, hp: 120, speed: 58, attackDamage: 11, attackRange: 40, attackSpeed: 0.6,
        armor: 4, magicResist: 1, xpReward: 60, goldReward: 32,
        aggroRange: 320, leashRange: 100000, aiBehavior: 'melee', _hunter: true, _horror: 'butcher',
    },
    hollow: {
        id: 'hollow', name: 'The Hollow', color: '#1a1a22', colorDark: '#050507', icon: '⌇',
        size: 46, hp: 80, speed: 76, attackDamage: 8, attackRange: 34, attackSpeed: 0.7,
        armor: 2, magicResist: 4, xpReward: 55, goldReward: 28,
        aggroRange: 400, leashRange: 100000, aiBehavior: 'melee', _hunter: true, _horror: 'hollow',
    },
    wraith: {
        id: 'wraith', name: 'The Wraith', color: '#244a52', colorDark: '#0e2226', icon: '࿔',
        size: 38, hp: 58, speed: 82, attackDamage: 7, attackRange: 220, attackSpeed: 0.6,
        armor: 0, magicResist: 7, xpReward: 50, goldReward: 26,
        aggroRange: 380, leashRange: 100000, aiBehavior: 'ranged_magic', _hunter: true, _horror: 'wraith',
    },
    effigy: {
        id: 'effigy', name: 'The Effigy', color: '#7a5a28', colorDark: '#3a2c12', icon: '✸',
        size: 40, hp: 75, speed: 70, attackDamage: 9, attackRange: 32, attackSpeed: 0.7,
        armor: 2, magicResist: 2, xpReward: 48, goldReward: 24,
        aggroRange: 330, leashRange: 100000, aiBehavior: 'melee', _hunter: true, _horror: 'effigy',
    },
    doll: {
        id: 'doll', name: 'The Marionette', color: '#d9c9b8', colorDark: '#7a6450', icon: '✄',
        size: 32, hp: 54, speed: 76, attackDamage: 7, attackRange: 200, attackSpeed: 0.7,
        armor: 1, magicResist: 3, xpReward: 42, goldReward: 21,
        aggroRange: 360, leashRange: 100000, aiBehavior: 'ranged_magic', _hunter: true, _horror: 'doll',
    },
    leech: {
        id: 'leech', name: 'The Parasite', color: '#8e2447', colorDark: '#4a1226', icon: '◉',
        size: 34, hp: 70, speed: 110, attackDamage: 8, attackRange: 28, attackSpeed: 0.9,
        armor: 1, magicResist: 2, xpReward: 44, goldReward: 22,
        aggroRange: 340, leashRange: 100000, aiBehavior: 'fast_chase', _hunter: true, _horror: 'leech',
    },
    wraithling: {
        id: 'wraithling', name: 'Wraithling', color: '#3a2a4a', colorDark: '#1a1226', icon: '·',
        size: 20, hp: 14, speed: 116, attackDamage: 3, attackRange: 24, attackSpeed: 1.0,
        armor: 0, magicResist: 1, xpReward: 4, goldReward: 1,
        aggroRange: 300, leashRange: 100000, aiBehavior: 'fast_chase', _horror: 'wraithling',
    },

    skeleton_minion: {
        id: 'skeleton_minion',
        name: 'Skeleton Minion',
        color: '#BDBDBD',
        colorDark: '#757575',
        icon: 'M',
        size: 24,
        hp: 25,
        speed: 80,
        attackDamage: 8,
        attackRange: 28,
        attackSpeed: 1.0,
        armor: 0,
        magicResist: 0,
        xpReward: 5,
        goldReward: 1,
        aggroRange: 300,
        leashRange: 1000,
        aiBehavior: 'fast_chase',
    },
    boss_dragon: {
        id: 'boss_dragon',
        name: 'Dragon Boss',
        color: '#D50000',
        colorDark: '#800000',
        icon: 'D',
        size: 48,
        hp: 350,
        speed: 50,
        attackDamage: 35,
        attackRange: 45,
        attackSpeed: 0.5,
        armor: 8,
        magicResist: 6,
        xpReward: 200,
        goldReward: 105,
        aggroRange: 400,
        leashRange: 600,
        aiBehavior: 'boss',
        _sprite: { gridCols: 4, frameSize: 48, states: { idle: [0,1,2,3], walk: [4,5,6,7], attack: [8,9,10,11], death: [12,13,14,15] } },
    },
};

// The 10 horror champions hunt from floor 1 onward — they ARE the nightmare.
const HORROR_CHAMPIONS = ['smiler', 'nun', 'crawler', 'weeper', 'butcher', 'hollow', 'wraith', 'effigy', 'doll', 'leech'];

/** Enemies available per dungeon floor range */
export const FLOOR_ENEMY_TABLES = {
    // Floors 1-2: the horrors arrive immediately, with a few fodder beasts.
    early: [...HORROR_CHAMPIONS, 'goblin', 'bat', 'slime'],
    // Floors 3-5
    mid: [...HORROR_CHAMPIONS, 'skeleton', 'orc_warrior', 'giant_spider'],
    // Floors 6-8
    late: [...HORROR_CHAMPIONS, 'demon_hound', 'necromancer', 'dark_knight', 'fire_elemental'],
    // Floors 9-10: everything + boss
    end: [...HORROR_CHAMPIONS, 'necromancer', 'dark_knight', 'fire_elemental', 'boss_dragon'],
};

/** Get enemy pool for a given floor */
export function getEnemyPoolForFloor(floorNumber) {
    if (floorNumber <= 2) return FLOOR_ENEMY_TABLES.early;
    if (floorNumber <= 5) return FLOOR_ENEMY_TABLES.mid;
    if (floorNumber <= 8) return FLOOR_ENEMY_TABLES.late;
    return FLOOR_ENEMY_TABLES.end;
}

/** Get a random enemy type for spawning */
export function getRandomEnemyType() {
    const keys = Object.keys(ENEMIES);
    return keys[Math.floor(Math.random() * keys.length)];
}

/** Get enemy config by type ID */
export function getEnemyConfig(type) {
    return ENEMIES[type] || ENEMIES.goblin;
}

/** Scale enemy stats based on floor number */
export function scaleEnemyForFloor(config, floorNumber) {
    const mult = 1 + (floorNumber - 1) * 0.15; // 15% per floor
    return {
        ...config,
        hp: Math.round(config.hp * mult),
        attackDamage: Math.round(config.attackDamage * mult),
        xpReward: Math.round(config.xpReward * mult),
        goldReward: Math.round(config.goldReward * mult),
    };
}