// spells.js — all spell definitions, keyed by spell ID
// rankScaling: damagePerRank multiplies base damage, cooldownPerRank subtracts from base cooldown (min 1s)

export const SPELLS = {
    // ==================== ORC ====================
    cleave: {
        id: 'cleave',
        name: 'Cleave',
        key: 'q',
        cooldown: 5,
        type: 'cone',
        range: 64,
        coneAngle: Math.PI / 3,
        damage: 35,
        adScaling: 0.6,
        castTime: 0.25,
        color: '#4CAF50',
        description: 'Sweep your weapon in a wide arc.',
        rankScaling: { damagePerRank: 0.35, cooldownPerRank: 0.6 },
    },
    stomp: {
        id: 'stomp',
        name: 'War Stomp',
        key: 'w',
        cooldown: 8,
        type: 'aoe_self',
        radius: 72,
        damage: 25,
        stunDuration: 0.75,
        castTime: 0.35,
        color: '#795548',
        description: 'Stun nearby enemies.',
        rankScaling: { damagePerRank: 0.35, cooldownPerRank: 0.8 },
    },
    charge: {
        id: 'charge',
        name: 'Charge',
        key: 'e',
        cooldown: 10,
        type: 'dash',
        range: 180,
        speed: 500,
        damage: 20,
        stunDuration: 0.3,
        castTime: 0.1,
        color: '#66BB6A',
        description: 'Rush forward, damaging the first enemy hit.',
        rankScaling: { damagePerRank: 0.4, cooldownPerRank: 1.0 },
    },
    berserk: {
        id: 'berserk',
        name: 'Berserker Rage',
        key: 'r',
        cooldown: 50,
        type: 'buff',
        duration: 5,
        attackSpeedMultiplier: 1.5,
        speedMultiplier: 1.3,
        damageMultiplier: 1.2,
        castTime: 0.2,
        color: '#F44336',
        description: 'Enter a frenzy of increased attack speed and damage.',
    },

    // ==================== ELF ====================
    shadow_strike: {
        id: 'shadow_strike',
        name: 'Shadow Strike',
        key: 'q',
        cooldown: 6,
        type: 'projectile',
        projectileSpeed: 400,
        range: 200,
        damage: 30,
        adScaling: 0.5,
        slowDuration: 1.5,
        slowAmount: 0.4,
        castTime: 0.2,
        color: '#7B1FA2',
        projectileColor: '#9C27B0',
        projectileSize: 6,
        description: 'Throw a shadowy blade that slows.',
        rankScaling: { damagePerRank: 0.35, cooldownPerRank: 0.6 },
    },
    vanish: {
        id: 'vanish',
        name: 'Vanish',
        key: 'w',
        cooldown: 12,
        type: 'buff',
        duration: 2,
        invisible: true,
        bonusDamage: 40,
        castTime: 0.15,
        color: '#4A148C',
        description: 'Become invisible; your next attack deals bonus damage.',
    },
    backstab: {
        id: 'backstab',
        name: 'Backstab',
        key: 'e',
        cooldown: 8,
        type: 'teleport',
        range: 150,
        damage: 35,
        adScaling: 0.7,
        behindTarget: true,
        castTime: 0.15,
        color: '#CE93D8',
        description: 'Teleport behind your target and strike.',
        rankScaling: { damagePerRank: 0.4, cooldownPerRank: 0.8 },
    },
    death_mark: {
        id: 'death_mark',
        name: 'Death Mark',
        key: 'r',
        cooldown: 45,
        type: 'mark',
        range: 150,
        markDuration: 3,
        baseDamage: 50,
        storedDamagePercent: 0.35,
        castTime: 0.2,
        color: '#E040FB',
        selfSpeedMult: 1.3,
        selfSpeedDuration: 2,
        description: 'Mark an enemy. After 3s, they take bonus damage based on damage dealt. Gain a burst of speed to chase them down.',
    },

    // ==================== PYRO ====================
    fireball: {
        id: 'fireball',
        name: 'Fireball',
        key: 'q',
        cooldown: 4,
        type: 'projectile',
        projectileSpeed: 350,
        range: 200,
        damage: 40,
        explosionRadius: 40,
        castTime: 0.3,
        color: '#FF5722',
        projectileColor: '#FF9800',
        projectileSize: 8,
        description: 'Launch a fireball that explodes on impact.',
        rankScaling: { damagePerRank: 0.35, cooldownPerRank: 0.4 },
    },
    flame_wall: {
        id: 'flame_wall',
        name: 'Flame Wall',
        key: 'w',
        cooldown: 10,
        type: 'ground_aoe',
        range: 110,
        wallLength: 100,
        duration: 4,
        damagePerSecond: 15,
        castTime: 0.3,
        color: '#FF5722',
        description: 'Create a wall of fire that burns enemies walking through.',
        rankScaling: { damagePerRank: 0.35, cooldownPerRank: 0.8 },
    },
    combustion: {
        id: 'combustion',
        name: 'Combustion',
        key: 'e',
        cooldown: 7,
        type: 'aoe_self',
        radius: 100,
        damage: 25,
        knockback: 150,
        bonusPerBurn: 15,
        castTime: 0.2,
        color: '#FF9800',
        description: 'Detonate all burning enemies for bonus damage.',
        rankScaling: { damagePerRank: 0.35, cooldownPerRank: 0.6 },
    },
    meteor: {
        id: 'meteor',
        name: 'Meteor Storm',
        key: 'r',
        cooldown: 50,
        type: 'meteor_storm',
        range: 200,
        radius: 80,
        damage: 110,
        waveCount: 4,
        waveInterval: 0.5,
        castTime: 0.5,
        color: '#F44336',
        description: 'Call down meteors in a large area over 2 seconds.',
    },

    // ==================== PALADIN ====================
    holy_strike: {
        id: 'holy_strike',
        name: 'Holy Strike',
        key: 'q',
        cooldown: 5,
        type: 'cone',
        range: 60,
        coneAngle: Math.PI / 4,
        damage: 25,
        healPercent: 0.5,
        castTime: 0.25,
        color: '#FDD835',
        description: 'Strike with holy light, damaging and healing yourself.',
        rankScaling: { damagePerRank: 0.35, cooldownPerRank: 0.6 },
    },
    shield_bash: {
        id: 'shield_bash',
        name: 'Shield Bash',
        key: 'w',
        cooldown: 8,
        type: 'cone',
        range: 48,
        coneAngle: Math.PI / 6,
        damage: 15,
        stunDuration: 0.6,
        shieldAmount: 40,
        shieldDuration: 3,
        castTime: 0.3,
        color: '#FFC107',
        description: 'Stun an enemy and gain a shield.',
        rankScaling: { damagePerRank: 0.4, cooldownPerRank: 0.8 },
    },
    divine_light: {
        id: 'divine_light',
        name: 'Divine Light',
        key: 'e',
        cooldown: 10,
        type: 'heal',
        healAmount: 30,
        healOverTime: 0.5,
        hotDuration: 3,
        castTime: 0.3,
        color: '#FFF176',
        description: 'Heal yourself over time.',
    },
    holy_nova: {
        id: 'holy_nova',
        name: 'Holy Nova',
        key: 'r',
        cooldown: 45,
        type: 'holy_nova',
        radius: 110,
        damage: 50,
        healAmount: 40,
        castTime: 0.4,
        color: '#FFEB3B',
        description: 'A burst of holy energy damages enemies and heals allies.',
        rankScaling: { damagePerRank: 0.35, cooldownPerRank: 1.0 },
    },
    // ==================== DEMON SLAYER ====================
    water_breathing: {
        id: 'water_breathing',
        name: 'Water Breathing',
        key: 'q',
        cooldown: 5,
        type: 'cone',
        range: 64,
        coneAngle: Math.PI / 3,
        damage: 30,
        adScaling: 0.5,
        slowAmount: 0.35,
        slowDuration: 2,
        castTime: 0.25,
        color: '#00BCD4',
        description: 'Flowing water slash that slows enemies.',
        rankScaling: { damagePerRank: 0.35, cooldownPerRank: 0.6 },
    },
    flame_breathing: {
        id: 'flame_breathing',
        name: 'Flame Breathing',
        key: 'w',
        cooldown: 8,
        type: 'buff',
        duration: 5,
        bonusDamage: 12,
        attackSpeedMultiplier: 1.2,
        castTime: 0.2,
        color: '#FF5722',
        description: 'Infuse your blade with fire — attacks apply burn for 5s.',
        rankScaling: { cooldownPerRank: 0.8 },
    },
    thunder_breathing: {
        id: 'thunder_breathing',
        name: 'Thunder Breathing',
        key: 'e',
        cooldown: 7,
        type: 'projectile',
        projectileSpeed: 600,
        range: 200,
        damage: 35,
        adScaling: 0.6,
        projectileSize: 8,
        castTime: 0.2,
        color: '#FFEB3B',
        projectileColor: '#FFF176',
        description: 'Lightning-fast ranged slash that pierces enemies.',
        rankScaling: { damagePerRank: 0.4, cooldownPerRank: 0.7 },
    },
    sun_dance: {
        id: 'sun_dance',
        name: 'Sun Breathing Dance',
        key: 'r',
        cooldown: 50,
        type: 'holy_nova',
        radius: 110,
        damage: 60,
        burnDuration: 4,
        burnDps: 12,
        castTime: 0.5,
        color: '#FF6F00',
        description: 'Spinning inferno that damages all around and leaves burning trails.',
        rankScaling: { damagePerRank: 0.35, cooldownPerRank: 1.0 },
    },

    // ==================== SHADOW HUNTER (precision marksman / kiter) ====================
    piercing_shot: {
        id: 'piercing_shot',
        name: 'Piercing Shot',
        key: 'q',
        cooldown: 5,
        type: 'projectile',
        projectileSpeed: 560,
        range: 280,
        damage: 32,
        adScaling: 0.6,
        projectileSize: 7,
        pierce: true,
        castTime: 0.25,
        color: '#78909C',
        projectileColor: '#B0BEC5',
        description: 'Fire a swift arrow that flies through every enemy in its path.',
        rankScaling: { damagePerRank: 0.35, cooldownPerRank: 0.6 },
    },
    hunters_focus: {
        id: 'hunters_focus',
        name: "Hunter's Focus",
        key: 'w',
        cooldown: 12,
        type: 'buff',
        duration: 5,
        attackSpeedMultiplier: 1.45,
        bonusDamage: 14,
        castTime: 0.15,
        color: '#90A4AE',
        description: 'Steady your aim: greatly increased attack speed and bonus shot damage for 5s.',
        rankScaling: { cooldownPerRank: 0.8 },
    },
    tumble: {
        id: 'tumble',
        name: 'Tumble',
        key: 'e',
        cooldown: 7,
        type: 'dash',
        range: 170,
        speed: 620,
        damage: 15,
        adScaling: 0.3,
        castTime: 0.05,
        color: '#B0BEC5',
        description: 'Roll a short distance to reposition, nicking any enemy you pass. Perfect for kiting.',
        rankScaling: { damagePerRank: 0.3, cooldownPerRank: 0.7 },
    },
    deadeye: {
        id: 'deadeye',
        name: 'Deadeye',
        key: 'r',
        cooldown: 40,
        type: 'projectile',
        projectileSpeed: 900,
        range: 700,
        damage: 130,
        adScaling: 1.0,
        projectileSize: 14,
        pierce: true,
        castTime: 0.5,
        color: '#ECEFF1',
        projectileColor: '#FFFFFF',
        description: 'Loose a single colossal arrow that pierces the entire battlefield, devastating all in its line.',
        rankScaling: { damagePerRank: 0.4, cooldownPerRank: 1.5 },
    },

    // ==================== RONIN ====================
    rasen_shuriken: {
        id: 'rasen_shuriken',
        name: 'Rasen Shuriken',
        key: 'q',
        cooldown: 5,
        type: 'projectile',
        projectileSpeed: 400,
        range: 200,
        damage: 35,
        explosionRadius: 35,
        slowAmount: 0.3,
        slowDuration: 1.5,
        projectileSize: 10,
        castTime: 0.25,
        color: '#00E5FF',
        projectileColor: '#18FFFF',
        description: 'Throws a spinning wind projectile that explodes and slows.',
        rankScaling: { damagePerRank: 0.35, cooldownPerRank: 0.6 },
    },
    shadow_clone: {
        id: 'shadow_clone',
        name: 'Shadow Clone',
        key: 'w',
        cooldown: 10,
        type: 'aoe_self',
        radius: 60,
        damage: 0,
        stunDuration: 0,
        castTime: 0.3,
        color: '#FF6D00',
        description: 'Create a decoy clone that taunts nearby enemies for 3s.',
        rankScaling: { cooldownPerRank: 1.0 },
    },
    fire_style: {
        id: 'fire_style',
        name: 'Fire Style',
        key: 'e',
        cooldown: 9,
        type: 'ground_aoe',
        range: 120,
        wallLength: 100,
        duration: 4,
        damagePerSecond: 18,
        castTime: 0.3,
        color: '#FF5722',
        description: 'Breathe a wall of flame that burns enemies passing through.',
        rankScaling: { damagePerRank: 0.35, cooldownPerRank: 0.8 },
    },
    sage_storm: {
        id: 'sage_storm',
        name: 'Sage Art: Storm',
        key: 'r',
        cooldown: 50,
        type: 'meteor_storm',
        range: 200,
        radius: 85,
        damage: 50,
        waveCount: 6,
        waveInterval: 0.35,
        castTime: 0.5,
        color: '#7C4DFF',
        description: 'Call down 6 lightning bolts in a large area over 2s.',
        rankScaling: { damagePerRank: 0.35, cooldownPerRank: 1.0 },
    },

    // ==================== SAIYAN ====================
    ki_wave: {
        id: 'ki_wave',
        name: 'Ki Wave',
        key: 'q',
        cooldown: 4,
        type: 'projectile',
        projectileSpeed: 450,
        range: 180,
        damage: 30,
        adScaling: 0.4,
        explosionRadius: 30,
        projectileSize: 9,
        castTime: 0.25,
        color: '#00E5FF',
        projectileColor: '#18FFFF',
        description: 'Fire a beam of ki energy that explodes on impact.',
        rankScaling: { damagePerRank: 0.35, cooldownPerRank: 0.4 },
    },
    instant_transmission: {
        id: 'instant_transmission',
        name: 'Instant Transmission',
        key: 'w',
        cooldown: 12,
        type: 'dash',
        range: 220,
        speed: 900,
        damage: 18,
        adScaling: 0.3,
        castTime: 0.05,
        grantBuffId: 'power_up',
        grantBuffDuration: 4,
        grantDamageMultiplier: 1.3,
        grantSpeedMultiplier: 1.2,
        color: '#FF1744',
        description: 'Vanish and reappear beside your target, striking them and powering up for 4s.',
        rankScaling: { damagePerRank: 0.4, cooldownPerRank: 1.0 },
    },
    kaioken_punch: {
        id: 'kaioken_punch',
        name: 'Kaioken Punch',
        key: 'e',
        cooldown: 7,
        type: 'cone',
        range: 56,
        coneAngle: Math.PI / 3,
        damage: 40,
        adScaling: 0.8,
        bonusPerBuff: 15,
        castTime: 0.3,
        color: '#FF1744',
        description: 'Devastating punch — more damage if Power Up is active.',
        rankScaling: { damagePerRank: 0.4, cooldownPerRank: 0.7 },
    },
    spirit_bomb: {
        id: 'spirit_bomb',
        name: 'Kamehameha',
        key: 'r',
        cooldown: 60,
        type: 'beam',
        range: 550,
        beamWidth: 90,
        damage: 180,
        adScaling: 1.3,
        castTime: 1.2,
        shakeIntensity: 24,
        color: '#00E5FF',
        projectileColor: '#E0FFFF',
        description: 'KA-ME-HA-ME-HA! Unleash a colossal beam that obliterates everything in a wide line — not a bolt, a wall of devastation that only grows with each rank.',
        rankScaling: {
            damagePerRank: 0.6,
            cooldownPerRank: 2.0,
            sizePerRank: 18,
        },
    },
};

/** Get default spell instance for a spell ID (with cooldown tracking) */
export function createSpellInstance(spellId) {
    const template = SPELLS[spellId];
    if (!template) return null;
    return {
        id: spellId,
        name: template.name,
        key: template.key,
        cooldown: 0,
        maxCooldown: template.cooldown,
        castTime: template.castTime || 0.25,
    };
}

/** Get default spell instances for a list of spell IDs */
export function createSpellKit(spellIds) {
    const kit = {};
    for (const id of spellIds) {
        kit[id.split('_')[0]] = createSpellInstance(id);
    }
    // Map keys properly: spells are stored by their key letter
    const result = { q: null, w: null, e: null, r: null };
    const keys = ['q', 'w', 'e', 'r'];
    for (let i = 0; i < Math.min(spellIds.length, 4); i++) {
        const inst = createSpellInstance(spellIds[i]);
        if (inst) {
            inst.key = keys[i];
            result[keys[i]] = inst;
        }
    }
    return result;
}
